---
title: ''
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(magrittr)
library(readr)
library(vroom)
library(devtools)
library(keyring)


#set pathnames
downloads_path = key_get("downloads_path")

#Source rselenium functions
devtools::source_url("https://github.com/hsteinberg/ccdph-functions/blob/master/general-use-rselenium-functions.R?raw=TRUE")
source("transfer-selenium.R")

```

```{r data}

#read in list of cases that have already been transferred so we can avoid repeated transfers
already_transferred = read_csv(paste0(downloads_path, Sys.Date(), "covid_transfers.csv"),
                     col_types = cols()) %>%
  set_colnames(c("caseNumber", "transferCount")) %>%
  filter(transferCount > 0)

#read in transfer logs from last week
last_week = (Sys.Date()-7):(Sys.Date()-1) %>% as.Date(origin = "1970-01-01") %>%
  paste0( ., "transferred_log.txt")
transferred_files = list.files("daily-transferred-cases") %>%
  intersect(last_week)
already_transferred_logs = lapply(paste0("daily-transferred-cases/",transferred_files), function(x){
  vroom(x, col_names = F) %>%
    pull(X1)
}) %>%
  unlist()


#don't transfer cases to chi unless they have a chi zip code
chi_zips = c("60601", "60602","60603","60604","60605","60606","60607","60608","60609","60610",
"60611","60612","60613","60614","60615","60616","60617","60618","60619","60620","60621","60622","60623","60624","60625","60626","60628","60629","60630","60631",
"60632","60633","60634","60636","60637","60638","60639","60640","60641","60642","60643","60644","60645","60646","60647","60649","60651","60652","60653","60654",
"60655","60656","60657","60659","60660","60661","60666","60707","60827","")

#read and clean BO report of cases assigned to CCDPH but have different counties listed
transfers = read_csv(paste0(downloads_path, Sys.Date(), "covid_other_counties.csv"),
                     col_types = cols()) %>%
  rename(caseNumber = `State Case Number`,
         address = `Address at Onset`,
         outbreakID = `Outbreak ID`,
         reporterComment = `Reporter Comment`,
         #fips = `FIPS County`,
         county = `County at Onset`,
         #currentCounty = `Current County`,
         openDate = `Open Date`,
         city = `City at Onset`,
         zip = `Zip at Onset`,
         addressType = `Current Address Type`,
         attendsResides = `Patient Attends/Resides`) %>%
  mutate(openDate = as.Date(openDate, format = "%Y/%m/%d")) %>%
  #filter(reporterComment == "Auto case entry") %>%
  filter(county != "Out Of State" & is.na(outbreakID) &
           !(caseNumber %in% already_transferred$caseNumber) &
           !(caseNumber %in% already_transferred_logs) &
           openDate > (Sys.Date() - 30) &
           is.na(Investigator),
         addressType == "Home" | is.na(addressType),
         is.na(attendsResides)
         ) %>%
  filter(!(city == "Chicago" & !(zip %in% chi_zips))) %>%
  mutate(transferTo = ifelse(county == "Cook", city, county))

```


```{r transfer}
#set inedss login credentials- only needs to be done once per user per computer
#key_set("idph_username") #IDPH username
#key_set("idph_portal") #IDPH password
#also may need to make a daily-transferred-cases folder in your directory if not already there if you want to store your logs there and don't specify where the logs go
#dir.create("daily-transferred-cases")


start_server() #start selenium server
login_inedss() #login to inedss

# #Switching focus to INEDSS tab   
# windows <- rD$getWindowHandles()   
# rD$switchToWindow(windows[[2]])

logfile = paste0("daily-transferred-cases/", Sys.Date(), "transferred_log.txt")
if(!file.exists(logfile)){close(file(logfile, open="w"))} #initialize logfile
#file.edit(logfile) #open file so you can track where you are

#loop to transfer all cases in transfers dataframe
continue = TRUE
c = 1
while(continue){ #for loop sometimes errors out, so put inside while
  try(for(i in c:nrow(transfers)){
    caseNumber = transfers$caseNumber[i]
    jurisdiction = transfers$transferTo[i]
    
    transfer(caseNumber = caseNumber, transferTo = jurisdiction, logfile = logfile)
    wait_page("My Cases")
  })
  #c = number of unique case numbers in logfile + 1
  c = (vroom(logfile, col_names = FALSE) %>% 
         filter(grepl("2\\d\\-", X1)) %>% pull(X1) %>% unique() %>% length()) + 1
  continue = ifelse(c <= nrow(transfers), TRUE, FALSE)
  print(Sys.time())
}


stop_server()

```
```{r delete-downloads}
to_delete = list.files(downloads_path, pattern = "covid_transfers.csv|covid_other_counties.csv", full.names = T)
for(i in 1:length(to_delete)){
  unlink(to_delete[i])
}

```


```{r jurisdiction_selections_list}
#get jurisdictions list from inside Transfer Case page of any case
# jurisdictions = rD$findElement(using = "css", value = "#jurisdiction")$selectTag()$text %>%
#   as.data.frame() %>%
#   set_colnames("selection") %>%
#   mutate(county = gsub(" County.*$| Department of Public Health| Health Department| City/County| Public Health District", "", selection),
#          county = gsub("Illinois Dept of Public Health Central Office", "IDPH", county)
#          )%>%
#   filter(!(selection %in% c("Cook County Jail for STDs Only", "Cook County Juvenile Det Center for STDs Only"))) %>%
#   rbind(c("Dewitt - Piatt B/C Health Department", "Piatt")) %>%
#   rbind(c("Dewitt - Piatt B/C Health Department", "Dewitt")) %>%
#   rbind(c("Champaign-Urbana Public Health District", "Champaign")) %>%
#   rbind(c("Southern Seven Health Department", "Alexander")) %>%
#   rbind(c("Southern Seven Health Department", "Hardin")) %>%
#   rbind(c("Southern Seven Health Department", "Johnson")) %>%
#   rbind(c("Southern Seven Health Department", "Massac")) %>%
#   rbind(c("Southern Seven Health Department", "Pope")) %>%
#   rbind(c("Southern Seven Health Department", "Pulaski")) %>%
#   rbind(c("Southern Seven Health Department", "Union")) %>%
#   rbind(c("Franklin-Williamson B/C Health Department", "Franklin")) %>%
#   rbind(c("Franklin-Williamson B/C Health Department", "Williamson")) 
#
# write_csv(jurisdictions, "jurisdiction_selections_list.csv")


```
